fix: keep sensor source and header ABI aligned

diff --git a/support/sg2002/build b/support/sg2002/build
--- a/support/sg2002/build
+++ b/support/sg2002/build
@@ -39,6 +39,41 @@ maixcdk_clean(){
   maixcdk clean
 }
 
+sync_sensor_abi(){
+  local sample_comm="$MAIXCDK_PATH/components/3rd_party/sophgo-middleware/sophgo-middleware/v2/sample/common/sample_comm.h"
+  local sample_comm_tmp
+  local removed_sensors=(
+    GCORE_GC030A_MIPI_480P_30FPS_10BIT
+    GCORE_GC4653_MIPI_720P_60FPS_10BIT
+    GCORE_OV2685_MIPI_1600x1200_30FPS_10BIT
+    OV_OS04A10_MIPI_4M_720P90_12BIT
+  )
+
+  if [ ! -f "$sample_comm" ]; then
+    echo -e "\e[36m[build] \e[31mMissing sensor header: $sample_comm\e[0m" >&2
+    return 1
+  fi
+
+  for sensor in "${removed_sensors[@]}"; do
+    sample_comm_tmp="$(mktemp "${sample_comm}.XXXXXX")" || return 1
+    sed "/^[[:space:]]*$sensor[[:space:]]*,/d" "$sample_comm" > "$sample_comm_tmp" || {
+      rm -f "$sample_comm_tmp"
+      return 1
+    }
+    mv "$sample_comm_tmp" "$sample_comm" || {
+      rm -f "$sample_comm_tmp"
+      return 1
+    }
+  done
+
+  for sensor in "${removed_sensors[@]}"; do
+    if grep -q "$sensor" "$sample_comm"; then
+      echo -e "\e[36m[build] \e[31mFailed to remove sensor: $sensor\e[0m" >&2
+      return 1
+    fi
+  done
+}
+
 case "$1" in
   update_lib)
     cp -rf $NanoKVM_PATH/support/sg2002/additional/kvm $MAIXCDK_PATH/components
@@ -46,9 +81,10 @@ case "$1" in
     cp -rf $NanoKVM_PATH/support/sg2002/additional/vision $MAIXCDK_PATH/components
     cp -f $NanoKVM_PATH/support/sg2002/additional/peripheral/port/maixcam/maix_i2c.cpp $MAIXCDK_PATH/components/peripheral/port/maixcam/maix_i2c.cpp
     cp -f $NanoKVM_PATH/support/sg2002/additional/sophgo-middleware/v2/sample/common/sample_common_sensor.c $MAIXCDK_PATH/components/3rd_party/sophgo-middleware/sophgo-middleware/v2/sample/common/
+    sync_sensor_abi || exit 1
 
     echo -e "\e[36m[build] \e[32mupdate_lib ok!\e[0m"
-    exit 1
+    exit 0
   ;;
   kvm_system)
     Project_Name="kvm_system"
@@ -103,17 +139,19 @@ then
       then
         echo -e "\e[36m[build] \e[32mDetected that the library has not been modified; first, move the library\e[0m"
         
-        mkdir $NanoKVM_PATH/support/sg2002/additional/original
+        mkdir -p $NanoKVM_PATH/support/sg2002/additional/original
         mv -f $MAIXCDK_PATH/components/vision $NanoKVM_PATH/support/sg2002/additional/original
         # mv $MAIXCDK_PATH/components/maixcam_lib $NanoKVM_PATH/support/sg2002/additional/original
         mv -f $MAIXCDK_PATH/components/peripheral/port/maixcam/maix_i2c.cpp $NanoKVM_PATH/support/sg2002/additional/original
         mv -f $MAIXCDK_PATH/components/3rd_party/sophgo-middleware/sophgo-middleware/v2/sample/common/sample_common_sensor.c $NanoKVM_PATH/support/sg2002/additional/original
+        cp -f $MAIXCDK_PATH/components/3rd_party/sophgo-middleware/sophgo-middleware/v2/sample/common/sample_comm.h $NanoKVM_PATH/support/sg2002/additional/original
       
         cp -rf $NanoKVM_PATH/support/sg2002/additional/kvm $MAIXCDK_PATH/components
         cp -rf $NanoKVM_PATH/support/sg2002/additional/kvm_mmf $MAIXCDK_PATH/components
         cp -rf $NanoKVM_PATH/support/sg2002/additional/vision $MAIXCDK_PATH/components
         cp -f $NanoKVM_PATH/support/sg2002/additional/peripheral/port/maixcam/maix_i2c.cpp $MAIXCDK_PATH/components/peripheral/port/maixcam/maix_i2c.cpp
         cp -f $NanoKVM_PATH/support/sg2002/additional/sophgo-middleware/v2/sample/common/sample_common_sensor.c $MAIXCDK_PATH/components/3rd_party/sophgo-middleware/sophgo-middleware/v2/sample/common/
+        sync_sensor_abi || exit 1
 
         echo -e "\e[36m[build] \e[32mMove the library completed!\e[0m"
       fi
